import React, { createContext, useContext, useState } from "react";

export type Language = "en" | "fr" | "it" | "de";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

// Traductions complètes
const translations = {
  en: {
    // Header
    "header.home": "Home",
    "header.designs": "Designs",
    "header.pricing": "Pricing",
    "header.login": "Login",
    "header.signup": "Sign Up",

    // Hero Section
    "hero.badge": "Premium invitation platform",
    "hero.title": "Create",
    "hero.title_highlight": "exceptional invitations",
    "hero.description":
      "Transform your events with personalized invitations designed by experts. Simple, fast and professional.",
    "hero.start": "Start for free",
    "hero.models": "View templates",
    "hero.models_count": "500+",
    "hero.models_label": "Premium Templates",
    "hero.clients_count": "25k+",
    "hero.clients_label": "Satisfied Clients",
    "hero.rating": "4.9",
    "hero.rating_label": "Client Reviews",

    // Features
    "features.title": "Why choose Everblue?",
    "features.description":
      "Discover the features that make our platform the ideal solution for your special events",
    "features.design": "Customizable Design",
    "features.design_desc": "Modify every detail to create a unique invitation",
    "features.speed": "Fast Creation",
    "features.speed_desc":
      "Generate professional invitations in just a few minutes",
    "features.download": "Unlimited Download",
    "features.download_desc": "Access all your designs in high quality",
    "features.share": "Easy Sharing",
    "features.share_desc": "Send your invitations by email or social media",

    // Catalog
    "catalog.title": "Our invitation templates",
    "catalog.description":
      "Discover our collection of premium templates designed by professional designers for all your special events",
    "catalog.search": "Search a template...",
    "catalog.all": "All",
    "catalog.wedding": "Wedding",
    "catalog.birthday": "Birthday",
    "catalog.professional": "Professional",
    "catalog.christmas": "Christmas",
    "catalog.baptism": "Baptism",
    "catalog.party": "Party",
    "catalog.found": "template(s) found",
    "catalog.filters": "More filters",
    "catalog.preview": "Preview",
    "catalog.customize": "Customize",
    "catalog.view_all": "View all templates",

    // Menu
    "menu.theme": "Theme",
    "menu.language": "Language",
    "menu.light": "Light",
    "menu.dark": "Dark",

    // EditCard
    "editCard.title": "Professional Card Editor",
    "editCard.subtitle": "Create stunning designs in just a few clicks",
    "editCard.dragToMove": "Drag to move",
    "editCard.emptyCanvas.title": "Blank card",
    "editCard.emptyCanvas.description": "Start by adding content or choose a professional template",
    "editCard.tabs.elements": "Elements",
    "editCard.tabs.background": "Background",
    "editCard.tabs.properties": "Properties",
    "editCard.elements.text": "Text",
    "editCard.elements.image": "Image",
    "editCard.elements.video": "Video",
    "editCard.elements.gif": "GIF",
    "editCard.elements.textVariables": "Text variables ({{name}}, {{email}}, etc.)",
    "editCard.background.backgroundColor": "Background color",
    "editCard.background.professionalTemplates": "Professional Templates",
    "editCard.background.customBackground": "Custom background image",
    "editCard.properties.title": "Properties",
    "editCard.properties.selectedType": "selected",
    "editCard.properties.noSelection.title": "No element selected",
    "editCard.properties.noSelection.description": "Click on an element in the editor to modify its properties",
    "editCard.properties.text.content": "Content",
    "editCard.properties.text.text": "Text",
    "editCard.properties.text.size": "Size",
    "editCard.properties.text.color": "Color",
    "editCard.properties.text.font": "Font (60+ available)",
    "editCard.properties.text.textShadow": "Text shadow",
    "editCard.properties.text.alignment": "Alignment",
    "editCard.properties.text.weight": "Weight",
    "editCard.properties.text.shadowOptions.none": "None",
    "editCard.properties.text.shadowOptions.light": "Light",
    "editCard.properties.text.shadowOptions.medium": "Medium",
    "editCard.properties.text.shadowOptions.strong": "Strong",
    "editCard.properties.text.shadowOptions.veryStrong": "Very strong",
    "editCard.properties.text.shadowOptions.whiteGlow": "White glow",
    "editCard.properties.text.shadowOptions.goldGlow": "Gold glow",
    "editCard.properties.text.shadowOptions.blackOutline": "Black outline",
    "editCard.properties.text.shadowOptions.goldOutline": "Gold outline",
    "editCard.properties.text.alignmentOptions.left": "Left",
    "editCard.properties.text.alignmentOptions.center": "Center",
    "editCard.properties.text.alignmentOptions.right": "Right",
    "editCard.properties.text.weightOptions.normal": "Normal",
    "editCard.properties.text.weightOptions.bold": "Bold",
    "editCard.properties.text.weightOptions.lighter": "Light",
    "editCard.properties.media.base": "Base",
    "editCard.properties.media.width": "Width",
    "editCard.properties.media.height": "Height",
    "editCard.properties.media.opacity": "Opacity",
    "editCard.properties.media.rotation": "Rotation",
    "editCard.properties.media.flip": "Flip",
    "editCard.properties.media.horizontal": "Horizontal",
    "editCard.properties.media.vertical": "Vertical",
    "editCard.properties.media.style": "Style",
    "editCard.properties.media.borderRadius": "Border radius",
    "editCard.properties.media.borderColor": "Border color",
    "editCard.properties.media.thickness": "Thickness",
    "editCard.properties.media.shadows": "Shadows",
    "editCard.properties.media.enableShadow": "Enable shadow",
    "editCard.properties.media.shadowColor": "Shadow color",
    "editCard.properties.media.blur": "Blur",
    "editCard.properties.media.offsetX": "Offset X",
    "editCard.properties.media.offsetY": "Offset Y",
    "editCard.properties.media.filters": "Filters",
    "editCard.properties.media.brightness": "Brightness",
    "editCard.properties.media.contrast": "Contrast",
    "editCard.properties.media.saturation": "Saturation",
    "editCard.properties.media.grayscale": "Grayscale",
    "editCard.properties.media.mediaControls": "Media Controls",
    "editCard.properties.media.play": "Play",
    "editCard.properties.media.pause": "Pause",
    "editCard.properties.media.sound": "Sound",
    "editCard.properties.media.mute": "Mute",
    "editCard.properties.media.autoPlay": "Auto play",
    "editCard.properties.media.loop": "Loop",
    "editCard.properties.media.useAsBackground": "Use as background",
    "editCard.properties.deleteElement": "Delete element",
    "editCard.chat.title": "Design Assistant",
    "editCard.chat.subtitle": "Creative AI",
    "editCard.chat.placeholder": "Describe your card or ask for improvements...",
    "editCard.chat.examples": "💡 Examples: \"birthday card\" or \"improve my design with a modern style\"",
    "editCard.chat.assistant": "AI Assistant",
    "editCard.chat.you": "You",
    "editCard.chat.apply": "✅ Apply",
    "editCard.chat.cancel": "↩️ Cancel",
    "editCard.templates.title": "🎨 Professional Templates",
    "editCard.templates.subtitle": "20+ designs with images, varied borders and realistic paper effect",
    "editCard.templates.categories.all": "All",
    "editCard.templates.categories.birthday": "Birthday",
    "editCard.templates.categories.wedding": "Wedding",
    "editCard.templates.categories.baptism": "Baptism",
    "editCard.templates.categories.easter": "Easter",
    "editCard.templates.categories.christmas": "Christmas",
    "editCard.templates.categories.elegant": "Elegant",
    "editCard.templates.categories.nature": "Nature",
    "editCard.templates.categories.minimal": "Minimal",
    "editCard.templates.close": "Close",

    // Navigation
    "nav.home": "Home",
    "nav.designs": "Designs",
    "nav.builder": "Builder",
    "nav.messages": "Messages",
    "nav.events": "Events",
    "nav.invitations": "Invitations",
    "nav.inbox": "Inbox",
    "nav.organizations": "Organizations",

    // Builder
    "builder.title": "Invitation Creation",
    "builder.subtitle": "Personalize your card and envelope",
    "builder.design": "Design",
    "builder.details": "Details",
    "builder.preview": "Preview",
    "builder.send": "Send",
    "builder.save": "Save",
    "builder.continue": "Continue",
    "builder.back": "Back",
    "builder.elements": "Elements",
    "builder.background": "Background",
    "builder.properties": "Properties",

    // Guests
    "guests.title": "Guest Management",
    "guests.subtitle": "Add and manage your guests for invitation sending",
    "guests.stats.total": "Total",
    "guests.stats.whatsapp": "WhatsApp",
    "guests.stats.email": "Email",
    "guests.stats.valid": "Valid",
    "guests.alerts.noGuests": "Start by adding guests or importing a list.",
    "guests.alerts.noValidGuests": "No valid guests. Please correct the information.",
    "guests.alerts.validGuests": "guest(s) ready to receive the invitation.",
    "guests.search.placeholder": "Search for a guest...",
    "guests.search.filterAll": "All channels",
    "guests.search.filterWhatsapp": "WhatsApp only",
    "guests.search.filterEmail": "Email only",
    "guests.import.title": "Import guests",
    "guests.import.csv": "CSV",
    "guests.import.google": "Google",
    "guests.import.excel": "Excel",
    "guests.import.icloud": "iCloud",
    "guests.import.csvDescription": "Expected format: Name, Email or Phone",
    "guests.import.connectGoogle": "Connect to Google Contacts",
    "guests.import.connectIcloud": "Connect to iCloud Contacts",
    "guests.import.excelNotAvailable": "Excel import will be available in the next version. Use CSV export for now.",
    "guests.import.serviceWillBeImplemented": "Import functionality from",
    "guests.import.importSuccess": "guests imported successfully!",
    "guests.import.importError": "Import error. Check the file format.",
    "guests.import.noGuestsToExport": "No guests to export",
    "guests.table.title": "Guest list",
    "guests.table.description": "guest(s) found",
    "guests.table.descriptionFiltered": "guest(s) found",
    "guests.table.headers.status": "Status",
    "guests.table.headers.channel": "Channel",
    "guests.table.headers.name": "Name & Surname",
    "guests.table.headers.contact": "Phone / Email",
    "guests.table.headers.countryCode": "Country Code",
    "guests.table.headers.actions": "Actions",
    "guests.table.status.new": "New",
    "guests.table.status.valid": "✓ Valid",
    "guests.table.status.invalid": "✗ Invalid",
    "guests.table.channels.whatsapp": "WhatsApp",
    "guests.table.channels.email": "Email",
    "guests.table.placeholders.name": "John Doe",
    "guests.table.placeholders.phone": "XX XX XX XX XX",
    "guests.table.placeholders.email": "john@example.com",
    "guests.table.actions.add": "Add",
    "guests.table.actions.edit": "Edit (double-click)",
    "guests.table.actions.delete": "Delete",
    "guests.table.actions.save": "Save",
    "guests.table.actions.cancel": "Cancel",
    "guests.table.empty.noResults": "No guests match your filters",
    "guests.table.empty.noGuests": "No guests yet. Add your first guest above.",
    "guests.form.validation.nameRequired": "Please enter a name",
    "guests.form.validation.invalidPhone": "Invalid phone number. Format: +XX XXX XX XX XX",
    "guests.form.validation.invalidEmail": "Invalid email address",
    "guests.form.confirmDelete": "Are you sure you want to delete this guest?",
    "guests.navigation.backToDesign": "← Back to design",
    "guests.navigation.continueToPreview": "Continue to preview →",

    // Preview
    "preview.title": "Invitation Preview",
    "preview.subtitle": "Check how your invitation will display for each guest",
    "preview.noGuest.title": "No guest found",
    "preview.noGuest.description": "Please return to the previous step to add guests.",
    "preview.noGuest.backButton": "← Back",
    "preview.configuration.title": "Configuration",
    "preview.configuration.subtitle": "Select a guest and a model",
    "preview.configuration.guestLabel": "Guest",
    "preview.configuration.modelLabel": "Design model",
    "preview.configuration.deviceLabel": "Preview on",
    "preview.configuration.devices.mobile": "Mobile",
    "preview.configuration.devices.tablet": "Tablet",
    "preview.configuration.devices.desktop": "Desktop",
    "preview.guestInfo.title": "Guest Information",
    "preview.guestInfo.location": "Location:",
    "preview.guestInfo.date": "Date:",
    "preview.guestInfo.time": "Time:",
    "preview.validation.warning": "Warning:",
    "preview.validation.success": "Perfect! All variables have been successfully replaced for this guest.",
    "preview.livePreview.title": "Live Preview",
    "preview.livePreview.description": "Visualization on",
    "preview.models.default.name": "Simple Preview",
    "preview.models.default.description": "Basic display",
    "preview.models.selectModel": "Select a model",
    "preview.navigation.backToDetails": "← Back to details",
    "preview.navigation.continueToSend": "Continue to send",
    "preview.fullPreview.title": "Full invitation preview",

    // Send
    "send.title": "Send Invitations",
    "send.subtitle": "Configure and send your invitations to guests",
    "send.noGuests": "No guests found. Please return to the previous step to add guests.",
    "send.noValidGuests": "No valid guests found for channel. Please check your guest data.",
    "send.summary.title": "Send Summary",
    "send.summary.subtitle": "Check information before sending",
    "send.summary.elements": "Elements",
    "send.summary.validGuests": "Valid guests",
    "send.summary.variables": "Variables",
    "send.summary.sendMode": "Send mode",
    "send.summary.personalized": "Personalized",
    "send.summary.group": "Group",
    "send.summary.personalizedMode": "Personalized",
    "send.sendMode.title": "Send Mode",
    "send.sendMode.subtitle": "Choose between group or personalized sending per guest",
    "send.sendMode.group.title": "Group Send",
    "send.sendMode.group.description": "Send the same message to all guests of a specific channel.",
    "send.sendMode.group.channelLabel": "Group send channel",
    "send.sendMode.group.whatsapp": "WhatsApp",
    "send.sendMode.group.email": "Email",
    "send.sendMode.group.subjectLabel": "Subject",
    "send.sendMode.group.messageLabel": "Group message",
    "send.sendMode.group.messagePlaceholder": "Write your message...",
    "send.sendMode.group.templates.casual": "Casual template",
    "send.sendMode.group.templates.formal": "Formal template",
    "send.sendMode.personalized.title": "Personalization per guest",
    "send.sendMode.personalized.description": "Enable personalization for each guest, then click the arrow to edit the message.",
    "send.sendMode.personalized.personalizedCount": "personalized message(s)",
    "send.sendMode.personalized.personalizeAll": "Personalize all",
    "send.sendMode.personalized.standardAll": "All standard",
    "send.sendMode.personalized.personalizedBadge": "Personalized",
    "send.sendMode.personalized.subjectLabel": "Message subject",
    "send.sendMode.personalized.messageLabel": "Personalized message for",
    "send.sendMode.personalized.messagePlaceholder": "Write your personalized message for...",
    "send.sendMode.personalized.templates.casual": "Casual",
    "send.sendMode.personalized.templates.formal": "Formal",
    "send.sendMode.personalized.templates.reminder": "Reminder",
    "send.sendMode.personalized.noValidGuests": "No valid guests to personalize messages.",
    "send.settings.title": "Send Settings",
    "send.settings.subtitle": "Configure technical sending details",
    "send.settings.channelLabel": "Technical send channel",
    "send.settings.subjectLabel": "Email subject",
    "send.settings.defaultSubjectLabel": "Default subject",
    "send.settings.subjectPlaceholder": "Ex: You are invited to our wedding!",
    "send.settings.eventLabel": "Associated event",
    "send.settings.eventOptions.new": "Create new event",
    "send.settings.eventOptions.event1": "Event 1",
    "send.settings.eventOptions.event2": "Event 2",
    "send.settings.eventOptions.event3": "Event 3",
    "send.settings.variablesTitle": "Available variables:",
    "send.preview.title": "Message Preview",
    "send.preview.subtitle": "Here's what will be sent to your guests",
    "send.preview.groupSend": "Group send",
    "send.preview.personalizedSend": "Personalized send",
    "send.preview.emailTo": "Email to",
    "send.preview.whatsappTo": "WhatsApp to",
    "send.preview.guests": "guests",
    "send.preview.completePreview": "COMPLETE PREVIEW",
    "send.preview.modelDescription": "This card model will be sent to your guests with personalized variables",
    "send.preview.emailDescription": "This invitation template will be sent by email with replaced variables",
    "send.preview.whatsappDescription": "This text message will be sent by WhatsApp to all contacts",
    "send.preview.personalizedDescription": "Messages will be personalized for each guest according to your settings",
    "send.action.title": "Send Action",
    "send.action.subtitle": "Launch sending your invitations",
    "send.action.sendButton": "Send to",
    "send.action.sendPersonalized": "Send personalized message(s)",
    "send.action.sending": "Sending...",
    "send.action.maxRecipientsError": "Number of recipients exceeds 500. Please reduce the number of guests.",
    "send.navigation.backToPreview": "← Back to Preview",
    "send.navigation.home": "Home",
    "send.channels.email": "Email",
    "send.channels.whatsapp": "WhatsApp",
    "send.channels.mms": "MMS",
    "send.defaults.invitationTitle": "My invitation",
    "send.defaults.emailSubject": "You are invited!",
    "send.defaults.defaultSubject": "You are invited to our event",
    "send.defaults.defaultBody": "Hello, you are invited to our event. See details below.",
    "send.defaults.subjectPlaceholder": "You are invited!",
    "send.defaults.messagePlaceholder": "Write your message...",
    "send.defaults.selectChannel": "Select a channel",
    "send.defaults.selectChannelError": "Please select a send channel",
    "send.defaults.subjectRequired": "Subject is required",
    "send.defaults.modelWillBeSent": "This card model will be sent to your guests with personalized variables",
    "send.defaults.personalizedToSend": "personalized message(s) to send",
    "send.defaults.noPersonalizedMessage": "No personalized message",
    "send.defaults.enablePersonalization": "Enable personalization to see preview",
    "send.defaults.whatsappWillBeSent": "This message will be sent via WhatsApp",

    // Builder
    "builder.title": "Invitation Creation",
    "builder.subtitle": "Personalize your card and envelope",
    "builder.editor": "Editor",
    "builder.steps.design": "Design",
    "builder.steps.details": "Details",
    "builder.steps.preview": "Preview",
    "builder.steps.send": "Send",
    "builder.actions.save": "Save",
    "builder.actions.saving": "Saving...",
    "builder.actions.saveModel": "Save model",
    "builder.actions.back": "Back",
    "builder.defaults.yourTextHere": "Your text here",
    "send.defaults.messageTemplates.whatsapp.casual": "Hi {name}! I invite you to my event on {date}. Reply to confirm!",
    "send.defaults.messageTemplates.whatsapp.formal": "Hello {name}, you are cordially invited to our event on {date}. We hope to see you there.",
    "send.defaults.messageTemplates.whatsapp.reminder": "Reminder: {name}, don't forget our event tomorrow!",
    "send.defaults.messageTemplates.email.casual": "Hi {name},\\n\\nYou are invited to my event!\\n\\nSee you soon!",
    "send.defaults.messageTemplates.email.formal": "Dear {name},\\n\\nWe have the pleasure to invite you to our event.\\n\\nBest regards,",
    "send.defaults.messageTemplates.email.invitation": "Dear {name},\\n\\nIt is with pleasure that I invite you to join this special event.",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.close": "Close",

    // HomePage - Hero Section
    "hero.badge": "Premium invitation platform",
    "hero.title_part1": "Create",
    "hero.title_part2": "invitations",
    "hero.title_part3": "exceptional",
    "hero.description": "Transform your events with personalized invitations designed by experts. Simple, fast and professional.",
    "hero.start_free": "Start for free",
    "hero.view_templates": "View templates",
    "hero.stats.templates": "Premium Templates",
    "hero.stats.clients": "Satisfied Clients",
    "hero.stats.reviews": "Client Reviews",
    "hero.invitation.title": "Sophie & Thomas",
    "hero.invitation.subtitle": "invite you to celebrate their union",
    "hero.invitation.date": "June 15, 2024",
    "hero.invitation.time": "6:30 PM",
    "hero.invitation.venue": "Palace of Versailles",
    "hero.invitation.room": "Ballroom",
    "hero.invitation.dress_code": "Dress code: Evening attire",

    // HomePage - Features
    "features.title": "Why choose Everblue?",
    "features.subtitle": "Discover the features that make our platform the ideal solution for your invitations",
    "features.design.title": "Customizable Design",
    "features.design.desc": "Modify every detail to create a unique invitation",
    "features.speed.title": "Fast Creation",
    "features.speed.desc": "Generate professional invitations in just a few minutes",
    "features.download.title": "Unlimited Download",
    "features.download.desc": "Access all your designs in high quality",
    "features.share.title": "Easy Sharing",
    "features.share.desc": "Send your invitations by email or social media",

    // HomePage - Catalog
    "catalog.title": "Our invitation templates",
    "catalog.subtitle": "Discover our collection of premium templates designed by professional designers for all your special events",
    "catalog.search": "Search a template...",
    "catalog.filters": "More filters",
    "catalog.view_all": "View all templates",
    "catalog.results": "template(s) found",
    "catalog.preview": "Preview",
    "catalog.customize": "Customize",
    "catalog.use": "Use",
    "catalog.popular": "Popular",
    "catalog.premium": "Premium",
    "catalog.rating": "4.8",
    "catalog.template_desc": "Elegant and fully customizable template",

    // Categories
    "category.all": "All",
    "category.wedding": "Wedding",
    "category.birthday": "Birthday",
    "category.professional": "Professional",
    "category.christmas": "Christmas",
    "category.baptism": "Baptism",
    "category.party": "Party",

    // Template Names
    "template.elegant_wedding": "Elegant Wedding",
    "template.festive_birthday": "Festive Birthday",
    "template.corporate_event": "Corporate Event",
    "template.christmas_celebration": "Christmas Celebration",
    "template.elegant_party": "Elegant Party",
    "template.angelic_baptism": "Angelic Baptism",
    "template.business_meeting": "Business Meeting",
    "template.romantic_wedding": "Romantic Wedding",
  },
  fr: {
    // Header
    "header.home": "Accueil",
    "header.designs": "Designs",
    "header.pricing": "Tarifs",
    "header.login": "Connexion",
    "header.signup": "S'inscrire",

    // Hero Section
    "hero.badge": "Plateforme premium d'invitations",
    "hero.title": "Créez des",
    "hero.title_highlight": "invitations exceptionnelles",
    "hero.description":
      "Transformez vos événements avec des invitations personnalisées conçues par des experts. Simple, rapide et professionnel.",
    "hero.start": "Commencer gratuitement",
    "hero.models": "Voir les modèles",
    "hero.models_count": "500+",
    "hero.models_label": "Modèles Premium",
    "hero.clients_count": "25k+",
    "hero.clients_label": "Clients satisfaits",
    "hero.rating": "4.9",
    "hero.rating_label": "Avis clients",

    // Features
    "features.title": "Pourquoi choisir Everblue ?",
    "features.description":
      "Découvrez les fonctionnalités qui font de notre plateforme la solution idéale pour vos événements spéciaux",
    "features.design": "Design Personnalisable",
    "features.design_desc":
      "Modifiez chaque détail pour créer une invitation unique",
    "features.speed": "Création Rapide",
    "features.speed_desc":
      "Générez des invitations professionnelles en quelques minutes",
    "features.download": "Téléchargement Illimité",
    "features.download_desc": "Accédez à tous vos designs en haute qualité",
    "features.share": "Partage Facile",
    "features.share_desc":
      "Envoyez vos invitations par email ou réseaux sociaux",

    // Catalog
    "catalog.title": "Nos modèles d'invitations",
    "catalog.description":
      "Découvrez notre collection de modèles premium conçus par des designers professionnels pour tous vos événements spéciaux",
    "catalog.search": "Rechercher un modèle...",
    "catalog.all": "Tous",
    "catalog.wedding": "Mariage",
    "catalog.birthday": "Anniversaire",
    "catalog.professional": "Professionnel",
    "catalog.christmas": "Noël",
    "catalog.baptism": "Baptême",
    "catalog.party": "Soirée",
    "catalog.found": "modèle(s) trouvé(s)",
    "catalog.filters": "Plus de filtres",
    "catalog.preview": "Aperçu",
    "catalog.customize": "Personnaliser",
    "catalog.view_all": "Voir tous les modèles",

    // Menu
    "menu.theme": "Thème",
    "menu.language": "Langue",
    "menu.light": "Clair",
    "menu.dark": "Sombre",

    // EditCard
    "editCard.title": "Éditeur de Carte Professionnelle",
    "editCard.subtitle": "Créez des designs époustouflants en quelques clics",
    "editCard.dragToMove": "Glissez pour déplacer",
    "editCard.emptyCanvas.title": "Carte vierge",
    "editCard.emptyCanvas.description": "Commencez par ajouter du contenu ou choisissez un modèle professionnel",
    "editCard.tabs.elements": "Éléments",
    "editCard.tabs.background": "Fond",
    "editCard.tabs.properties": "Propriétés",
    "editCard.elements.text": "Texte",
    "editCard.elements.image": "Image",
    "editCard.elements.video": "Vidéo",
    "editCard.elements.gif": "GIF",
    "editCard.elements.textVariables": "Variables de texte ({{nom}}, {{email}}, etc.)",
    "editCard.background.backgroundColor": "Couleur de fond",
    "editCard.background.professionalTemplates": "Modèles Professionnels",
    "editCard.background.customBackground": "Image de fond personnalisée",
    "editCard.properties.title": "Propriétés",
    "editCard.properties.selectedType": "sélectionné",
    "editCard.properties.noSelection.title": "Aucun élément sélectionné",
    "editCard.properties.noSelection.description": "Cliquez sur un élément dans l'éditeur pour modifier ses propriétés",
    "editCard.properties.text.content": "Contenu",
    "editCard.properties.text.text": "Texte",
    "editCard.properties.text.size": "Taille",
    "editCard.properties.text.color": "Couleur",
    "editCard.properties.text.font": "Police (60+ disponibles)",
    "editCard.properties.text.textShadow": "Ombre du texte",
    "editCard.properties.text.alignment": "Alignement",
    "editCard.properties.text.weight": "Poids",
    "editCard.properties.text.shadowOptions.none": "Aucune",
    "editCard.properties.text.shadowOptions.light": "Légère",
    "editCard.properties.text.shadowOptions.medium": "Moyenne",
    "editCard.properties.text.shadowOptions.strong": "Forte",
    "editCard.properties.text.shadowOptions.veryStrong": "Très forte",
    "editCard.properties.text.shadowOptions.whiteGlow": "Lueur blanche",
    "editCard.properties.text.shadowOptions.goldGlow": "Lueur dorée",
    "editCard.properties.text.shadowOptions.blackOutline": "Contour noir",
    "editCard.properties.text.shadowOptions.goldOutline": "Contour doré",
    "editCard.properties.text.alignmentOptions.left": "Gauche",
    "editCard.properties.text.alignmentOptions.center": "Centre",
    "editCard.properties.text.alignmentOptions.right": "Droite",
    "editCard.properties.text.weightOptions.normal": "Normal",
    "editCard.properties.text.weightOptions.bold": "Gras",
    "editCard.properties.text.weightOptions.lighter": "Fin",
    "editCard.properties.media.base": "Base",
    "editCard.properties.media.width": "Largeur",
    "editCard.properties.media.height": "Hauteur",
    "editCard.properties.media.opacity": "Opacité",
    "editCard.properties.media.rotation": "Rotation",
    "editCard.properties.media.flip": "Flip",
    "editCard.properties.media.horizontal": "Horizontal",
    "editCard.properties.media.vertical": "Vertical",
    "editCard.properties.media.style": "Style",
    "editCard.properties.media.borderRadius": "Bordure arrondie",
    "editCard.properties.media.borderColor": "Couleur bordure",
    "editCard.properties.media.thickness": "Épaisseur",
    "editCard.properties.media.shadows": "Ombres",
    "editCard.properties.media.enableShadow": "Activer l'ombre",
    "editCard.properties.media.shadowColor": "Couleur ombre",
    "editCard.properties.media.blur": "Flou",
    "editCard.properties.media.offsetX": "Décalage X",
    "editCard.properties.media.offsetY": "Décalage Y",
    "editCard.properties.media.filters": "Filtres",
    "editCard.properties.media.brightness": "Luminosité",
    "editCard.properties.media.contrast": "Contraste",
    "editCard.properties.media.saturation": "Saturation",
    "editCard.properties.media.grayscale": "Niveaux de gris",
    "editCard.properties.media.mediaControls": "Contrôles Média",
    "editCard.properties.media.play": "Lecture",
    "editCard.properties.media.pause": "Pause",
    "editCard.properties.media.sound": "Son",
    "editCard.properties.media.mute": "Mute",
    "editCard.properties.media.autoPlay": "Lecture auto",
    "editCard.properties.media.loop": "Boucle",
    "editCard.properties.media.useAsBackground": "Utiliser comme fond d'écran",
    "editCard.properties.deleteElement": "Supprimer l'élément",
    "editCard.chat.title": "Assistant Design",
    "editCard.chat.subtitle": "IA créative",
    "editCard.chat.placeholder": "Décrivez votre carte ou demandez des améliorations...",
    "editCard.chat.examples": "💡 Exemples : \"carte d'anniversaire\" ou \"améliore mon design avec un style moderne\"",
    "editCard.chat.assistant": "Assistant IA",
    "editCard.chat.you": "Vous",
    "editCard.chat.apply": "✅ Appliquer",
    "editCard.chat.cancel": "↩️ Annuler",
    "editCard.templates.title": "🎨 Modèles Professionnels",
    "editCard.templates.subtitle": "20+ designs avec images, bordures variées et effet papier réaliste",
    "editCard.templates.categories.all": "Tous",
    "editCard.templates.categories.birthday": "Anniversaire",
    "editCard.templates.categories.wedding": "Mariage",
    "editCard.templates.categories.baptism": "Baptême",
    "editCard.templates.categories.easter": "Pâques",
    "editCard.templates.categories.christmas": "Noël",
    "editCard.templates.categories.elegant": "Élégant",
    "editCard.templates.categories.nature": "Nature",
    "editCard.templates.categories.minimal": "Minimal",
    "editCard.templates.close": "Fermer",

    // Navigation
    "nav.home": "Accueil",
    "nav.designs": "Designs",
    "nav.builder": "Créateur",
    "nav.messages": "Messages",
    "nav.events": "Événements",
    "nav.invitations": "Invitations",
    "nav.inbox": "Boîte de réception",
    "nav.organizations": "Organisations",

    // Builder
    "builder.title": "Création de l'invitation",
    "builder.subtitle": "Personnalisez votre carte et votre enveloppe",
    "builder.design": "Design",
    "builder.details": "Détails",
    "builder.preview": "Prévisualisation",
    "builder.send": "Envoi",
    "builder.save": "Enregistrer",
    "builder.continue": "Continuer",
    "builder.back": "Retour",
    "builder.elements": "Éléments",
    "builder.background": "Fond",
    "builder.properties": "Propriétés",

    // Guests
    "guests.title": "Gestion des invités",
    "guests.subtitle": "Ajoutez et gérez vos invités pour l'envoi des invitations",
    "guests.stats.total": "Total",
    "guests.stats.whatsapp": "WhatsApp",
    "guests.stats.email": "Email",
    "guests.stats.valid": "Valides",
    "guests.alerts.noGuests": "Commencez par ajouter des invités ou importer une liste.",
    "guests.alerts.noValidGuests": "Aucun invité valide. Veuillez corriger les informations.",
    "guests.alerts.validGuests": "invité(s) prêt(s) à recevoir l'invitation.",
    "guests.search.placeholder": "Rechercher un invité...",
    "guests.search.filterAll": "Tous les canaux",
    "guests.search.filterWhatsapp": "WhatsApp uniquement",
    "guests.search.filterEmail": "Email uniquement",
    "guests.import.title": "Importer des invités",
    "guests.import.csv": "CSV",
    "guests.import.google": "Google",
    "guests.import.excel": "Excel",
    "guests.import.icloud": "iCloud",
    "guests.import.csvDescription": "Format attendu : Nom, Email ou Téléphone",
    "guests.import.connectGoogle": "Se connecter à Google Contacts",
    "guests.import.connectIcloud": "Se connecter à iCloud Contacts",
    "guests.import.excelNotAvailable": "L'import Excel sera disponible dans la prochaine version. Utilisez l'export CSV pour le moment.",
    "guests.import.serviceWillBeImplemented": "Fonctionnalité d'import depuis",
    "guests.import.importSuccess": "invités importés avec succès !",
    "guests.import.importError": "Erreur lors de l'import. Vérifiez le format du fichier.",
    "guests.import.noGuestsToExport": "Aucun invité à exporter",
    "guests.table.title": "Liste des invités",
    "guests.table.description": "invité(s) trouvé(s)",
    "guests.table.descriptionFiltered": "invité(s) trouvé(s)",
    "guests.table.headers.status": "Statut",
    "guests.table.headers.channel": "Canal",
    "guests.table.headers.name": "Nom & Prénom",
    "guests.table.headers.contact": "Téléphone / Email",
    "guests.table.headers.countryCode": "Indicatif",
    "guests.table.headers.actions": "Actions",
    "guests.table.status.new": "Nouveau",
    "guests.table.status.valid": "✓ Valide",
    "guests.table.status.invalid": "✗ Invalide",
    "guests.table.channels.whatsapp": "WhatsApp",
    "guests.table.channels.email": "Email",
    "guests.table.placeholders.name": "Jean Dupont",
    "guests.table.placeholders.phone": "XX XX XX XX XX",
    "guests.table.placeholders.email": "jean@example.com",
    "guests.table.actions.add": "Ajouter",
    "guests.table.actions.edit": "Modifier (double-clic)",
    "guests.table.actions.delete": "Supprimer",
    "guests.table.actions.save": "Sauvegarder",
    "guests.table.actions.cancel": "Annuler",
    "guests.table.empty.noResults": "Aucun invité ne correspond à vos filtres",
    "guests.table.empty.noGuests": "Aucun invité pour le moment. Ajoutez votre premier invité ci-dessus.",
    "guests.form.validation.nameRequired": "Veuillez entrer un nom",
    "guests.form.validation.invalidPhone": "Numéro de téléphone invalide. Format: +XX XXX XX XX XX",
    "guests.form.validation.invalidEmail": "Adresse email invalide",
    "guests.form.confirmDelete": "Êtes-vous sûr de vouloir supprimer cet invité ?",
    "guests.navigation.backToDesign": "← Retour au design",
    "guests.navigation.continueToPreview": "Continuer vers la prévisualisation →",

    // Preview
    "preview.title": "Prévisualisation de l'invitation",
    "preview.subtitle": "Vérifiez comment votre invitation s'affichera pour chaque invité",
    "preview.noGuest.title": "Aucun invité trouvé",
    "preview.noGuest.description": "Veuillez retourner à l'étape précédente pour ajouter des invités.",
    "preview.noGuest.backButton": "← Retour",
    "preview.configuration.title": "Configuration",
    "preview.configuration.subtitle": "Sélectionnez un invité et un modèle",
    "preview.configuration.guestLabel": "Invité",
    "preview.configuration.modelLabel": "Modèle de design",
    "preview.configuration.deviceLabel": "Aperçu sur",
    "preview.configuration.devices.mobile": "Mobile",
    "preview.configuration.devices.tablet": "Tablette",
    "preview.configuration.devices.desktop": "Desktop",
    "preview.guestInfo.title": "Informations de l'invité",
    "preview.guestInfo.location": "Lieu:",
    "preview.guestInfo.date": "Date:",
    "preview.guestInfo.time": "Heure:",
    "preview.validation.warning": "Attention:",
    "preview.validation.success": "Parfait! Toutes les variables ont été remplacées avec succès pour cet invité.",
    "preview.livePreview.title": "Aperçu en direct",
    "preview.livePreview.description": "Visualisation sur",
    "preview.models.default.name": "Aperçu Simple",
    "preview.models.default.description": "Affichage basique",
    "preview.models.selectModel": "Sélectionnez un modèle",
    "preview.navigation.backToDetails": "← Retour aux détails",
    "preview.navigation.continueToSend": "Continuer vers l'envoi",
    "preview.fullPreview.title": "Aperçu complet de l'invitation",

    // Send
    "send.title": "Envoi des invitations",
    "send.subtitle": "Configurez et envoyez vos invitations aux invités",
    "send.noGuests": "Aucun invité trouvé. Veuillez retourner à l'étape précédente pour ajouter des invités.",
    "send.noValidGuests": "Aucun invité valide trouvé pour le canal. Veuillez vérifier les données de vos invités.",
    "send.summary.title": "Résumé de l'envoi",
    "send.summary.subtitle": "Vérifiez les informations avant d'envoyer",
    "send.summary.elements": "Éléments",
    "send.summary.validGuests": "Invités valides",
    "send.summary.variables": "Variables",
    "send.summary.sendMode": "Mode d'envoi",
    "send.summary.personalized": "Personnalisés",
    "send.summary.group": "Groupé",
    "send.summary.personalizedMode": "Personnalisé",
    "send.sendMode.title": "Mode d'envoi",
    "send.sendMode.subtitle": "Choisissez entre envoi groupé ou personnalisé par invité",
    "send.sendMode.group.title": "Envoi groupé",
    "send.sendMode.group.description": "Envoyez le même message à tous les invités d'un canal spécifique.",
    "send.sendMode.group.channelLabel": "Canal d'envoi groupé",
    "send.sendMode.group.whatsapp": "WhatsApp",
    "send.sendMode.group.email": "Email",
    "send.sendMode.group.subjectLabel": "Sujet",
    "send.sendMode.group.messageLabel": "Message groupé",
    "send.sendMode.group.messagePlaceholder": "Écrivez votre message...",
    "send.sendMode.group.templates.casual": "Template informel",
    "send.sendMode.group.templates.formal": "Template formel",
    "send.sendMode.personalized.title": "Personnalisation par invité",
    "send.sendMode.personalized.description": "Activez la personnalisation pour chaque invité, puis cliquez sur la flèche pour éditer le message.",
    "send.sendMode.personalized.personalizedCount": "message(s) personnalisé(s)",
    "send.sendMode.personalized.personalizeAll": "Personnaliser tous",
    "send.sendMode.personalized.standardAll": "Tout standard",
    "send.sendMode.personalized.personalizedBadge": "Personnalisé",
    "send.sendMode.personalized.subjectLabel": "Sujet du message",
    "send.sendMode.personalized.messageLabel": "Message personnalisé pour",
    "send.sendMode.personalized.messagePlaceholder": "Écrivez votre message personnalisé pour...",
    "send.sendMode.personalized.templates.casual": "Informel",
    "send.sendMode.personalized.templates.formal": "Formel",
    "send.sendMode.personalized.templates.reminder": "Rappel",
    "send.sendMode.personalized.noValidGuests": "Aucun invité valide pour personnaliser les messages.",
    "send.settings.title": "Paramètres d'envoi",
    "send.settings.subtitle": "Configurez les détails techniques de l'envoi",
    "send.settings.channelLabel": "Canal technique d'envoi",
    "send.settings.subjectLabel": "Sujet de l'email",
    "send.settings.defaultSubjectLabel": "Sujet par défaut",
    "send.settings.subjectPlaceholder": "Ex: Vous êtes invité à notre mariage!",
    "send.settings.eventLabel": "Événement associé",
    "send.settings.eventOptions.new": "Créer un nouvel événement",
    "send.settings.eventOptions.event1": "Événement 1",
    "send.settings.eventOptions.event2": "Événement 2",
    "send.settings.eventOptions.event3": "Événement 3",
    "send.settings.variablesTitle": "Variables disponibles:",
    "send.preview.title": "Aperçu du message",
    "send.preview.subtitle": "Voici ce qui sera envoyé à vos invités",
    "send.preview.groupSend": "Envoi groupé",
    "send.preview.personalizedSend": "Envoi personnalisé",
    "send.preview.emailTo": "Email à",
    "send.preview.whatsappTo": "WhatsApp à",
    "send.preview.guests": "invités",
    "send.preview.completePreview": "APERÇU COMPLET",
    "send.preview.modelDescription": "Ce modèle de carte sera envoyé à vos invités avec les variables personnalisées",
    "send.preview.emailDescription": "Ce modèle d'invitation sera envoyé par email avec les variables remplacées",
    "send.preview.whatsappDescription": "Ce message texte sera envoyé par WhatsApp à tous les contacts",
    "send.preview.personalizedDescription": "Les messages seront personnalisés pour chaque invité selon vos paramètres",
    "send.action.title": "Action d'envoi",
    "send.action.subtitle": "Lancez l'envoi de vos invitations",
    "send.action.sendButton": "Envoyer groupé à",
    "send.action.sendPersonalized": "Envoyer message(s) personnalisé(s)",
    "send.action.sending": "Envoi en cours...",
    "send.action.maxRecipientsError": "Le nombre de destinataires dépasse 500. Veuillez réduire le nombre d'invités.",
    "send.navigation.backToPreview": "← Retour Prévisualisation",
    "send.navigation.home": "Accueil",
    "send.channels.email": "Email",
    "send.channels.whatsapp": "WhatsApp",
    "send.channels.mms": "MMS",
    "send.defaults.invitationTitle": "Mon invitation",
    "send.defaults.emailSubject": "Vous êtes invité!",
    "send.defaults.defaultSubject": "Vous êtes invité à notre événement",
    "send.defaults.defaultBody": "Bonjour, vous êtes invité à notre événement. Voir les détails ci-dessous.",
    "send.defaults.subjectPlaceholder": "Vous êtes invité!",
    "send.defaults.messagePlaceholder": "Écrivez votre message...",
    "send.defaults.selectChannel": "Sélectionner un canal",
    "send.defaults.selectChannelError": "Veuillez sélectionner un canal d'envoi",
    "send.defaults.subjectRequired": "Le sujet est requis",
    "send.defaults.modelWillBeSent": "Ce modèle de carte sera envoyé à vos invités avec les variables personnalisées",
    "send.defaults.personalizedToSend": "message(s) personnalisé(s) à envoyer",
    "send.defaults.noPersonalizedMessage": "Aucun message personnalisé",
    "send.defaults.enablePersonalization": "Activez la personnalisation pour voir l'aperçu",
    "send.defaults.whatsappWillBeSent": "Ce message sera envoyé via WhatsApp",

    // Builder
    // "builder.title": "Création de l'invitation",
    // "builder.subtitle": "Personnalisez votre carte et votre enveloppe",
    "builder.editor": "Éditeur",
    "builder.steps.design": "Design",
    "builder.steps.details": "Détails",
    "builder.steps.preview": "Prévisualisation",
    "builder.steps.send": "Envoi",
    "builder.actions.save": "Sauvegarder",
    "builder.actions.saving": "Sauvegarde...",
    "builder.actions.saveModel": "Sauvegarder le modèle",
    "builder.actions.back": "Retour",
    "builder.defaults.yourTextHere": "Votre texte ici",
    "send.defaults.messageTemplates.whatsapp.casual": "Salut {name} ! Je t'invite à mon événement le {date}. Réponds-moi pour confirmer !",
    "send.defaults.messageTemplates.whatsapp.formal": "Bonjour {name}, vous êtes cordialement invité(e) à notre événement du {date}. Nous espérons vous y voir.",
    "send.defaults.messageTemplates.whatsapp.reminder": "Rappel : {name}, n'oubliez pas notre événement demain !",
    "send.defaults.messageTemplates.email.casual": "Salut {name},\\n\\nTu es invité à mon événement !\\n\\nÀ bientôt !",
    "send.defaults.messageTemplates.email.formal": "Madame, Monsieur {name},\\n\\nNous avons le plaisir de vous convier à notre événement.\\n\\nCordialement,",
    "send.defaults.messageTemplates.email.invitation": "Cher(e) {name},\\n\\nC'est avec plaisir que je vous invite à rejoindre cet événement spécial.",

    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.confirm": "Confirmer",
    "common.close": "Fermer",

    // HomePage - Hero Section
    "hero.badge": "Plateforme premium d'invitations",
    "hero.title_part1": "Créez des",
    "hero.title_part2": "invitations",
    "hero.title_part3": "exceptionnelles",
    "hero.description": "Transformez vos événements avec des invitations personnalisées conçues par des experts. Simple, rapide et professionnel.",
    "hero.start_free": "Commencer gratuitement",
    "hero.view_templates": "Voir les modèles",
    "hero.stats.templates": "Modèles Premium",
    "hero.stats.clients": "Clients satisfaits",
    "hero.stats.reviews": "Avis clients",
    "hero.invitation.title": "Sophie & Thomas",
    "hero.invitation.subtitle": "vous invitent à célébrer leur union",
    "hero.invitation.date": "15 Juin 2024",
    "hero.invitation.time": "18h30",
    "hero.invitation.venue": "Château de Versailles",
    "hero.invitation.room": "Salle des Fêtes",
    "hero.invitation.dress_code": "Code vestimentaire : Tenue de soirée",

    // HomePage - Features
    "features.title": "Pourquoi choisir Everblue ?",
    "features.subtitle": "Découvrez les fonctionnalités qui font de notre plateforme la solution idéale pour vos invitations",
    "features.design.title": "Design Personnalisable",
    "features.design.desc": "Modifiez chaque détail pour créer une invitation unique",
    "features.speed.title": "Création Rapide",
    "features.speed.desc": "Générez des invitations professionnelles en quelques minutes",
    "features.download.title": "Téléchargement Illimité",
    "features.download.desc": "Accédez à tous vos designs en haute qualité",
    "features.share.title": "Partage Facile",
    "features.share.desc": "Envoyez vos invitations par email ou réseaux sociaux",

    // HomePage - Catalog
    "catalog.title": "Nos modèles d'invitations",
    "catalog.subtitle": "Découvrez notre collection de modèles premium conçus par des designers professionnels pour tous vos événements spéciaux",
    "catalog.search": "Rechercher un modèle...",
    "catalog.filters": "Plus de filtres",
    "catalog.view_all": "Voir tous les modèles",
    "catalog.results": "modèle(s) trouvé(s)",
    "catalog.preview": "Aperçu",
    "catalog.customize": "Personnaliser",
    "catalog.use": "Utiliser",
    "catalog.popular": "Populaire",
    "catalog.premium": "Premium",
    "catalog.rating": "4.8",
    "catalog.template_desc": "Modèle élégant et entièrement personnalisable",

    // Categories
    "category.all": "Tous",
    "category.wedding": "Mariage",
    "category.birthday": "Anniversaire",
    "category.professional": "Professionnel",
    "category.christmas": "Noël",
    "category.baptism": "Baptême",
    "category.party": "Soirée",

    // Template Names
    "template.elegant_wedding": "Mariage Élégant",
    "template.festive_birthday": "Anniversaire Festif",
    "template.corporate_event": "Événement d'Entreprise",
    "template.christmas_celebration": "Célébration de Noël",
    "template.elegant_party": "Soirée Élégante",
    "template.angelic_baptism": "Baptême Angélique",
    "template.business_meeting": "Réunion d'Affaires",
    "template.romantic_wedding": "Mariage Romantique",
  },
  it: {
    // Header
    "header.home": "Home",
    "header.designs": "Design",
    "header.pricing": "Prezzi",
    "header.login": "Accedi",
    "header.signup": "Iscriviti",

    // Hero Section
    "hero.badge": "Piattaforma premium di inviti",
    "hero.title": "Crea",
    "hero.title_highlight": "inviti straordinari",
    "hero.description":
      "Trasforma i tuoi eventi con inviti personalizzati progettati da esperti. Semplice, veloce e professionale.",
    "hero.start": "Inizia gratuitamente",
    "hero.models": "Visualizza modelli",
    "hero.models_count": "500+",
    "hero.models_label": "Modelli Premium",
    "hero.clients_count": "25k+",
    "hero.clients_label": "Clienti Soddisfatti",
    "hero.rating": "4.9",
    "hero.rating_label": "Recensioni Clienti",

    // Features
    "features.title": "Perché scegliere Everblue?",
    "features.description":
      "Scopri le funzionalità che rendono la nostra piattaforma la soluzione ideale per i tuoi eventi speciali",
    "features.design": "Design Personalizzabile",
    "features.design_desc":
      "Modifica ogni dettaglio per creare un invito unico",
    "features.speed": "Creazione Veloce",
    "features.speed_desc":
      "Genera inviti professionali in pochi minuti",
    "features.download": "Download Illimitato",
    "features.download_desc": "Accedi a tutti i tuoi design in alta qualità",
    "features.share": "Condivisione Facile",
    "features.share_desc":
      "Invia i tuoi inviti via email o social media",

    // Catalog
    "catalog.title": "I nostri modelli di inviti",
    "catalog.description":
      "Scopri la nostra collezione di modelli premium progettati da designer professionisti per tutti i tuoi eventi speciali",
    "catalog.search": "Cerca un modello...",
    "catalog.all": "Tutti",
    "catalog.wedding": "Matrimonio",
    "catalog.birthday": "Compleanno",
    "catalog.professional": "Professionale",
    "catalog.christmas": "Natale",
    "catalog.baptism": "Battesimo",
    "catalog.party": "Festa",
    "catalog.found": "modello(i) trovato(i)",
    "catalog.filters": "Altri filtri",
    "catalog.preview": "Anteprima",
    "catalog.customize": "Personalizza",
    "catalog.view_all": "Visualizza tutti i modelli",

    // Menu
    "menu.theme": "Tema",
    "menu.language": "Lingua",
    "menu.light": "Chiaro",
    "menu.dark": "Scuro",

    // EditCard
    "editCard.title": "Editor di Carte Professionali",
    "editCard.subtitle": "Crea design straordinari con pochi clic",
    "editCard.dragToMove": "Trascina per spostare",
    "editCard.emptyCanvas.title": "Carta vuota",
    "editCard.emptyCanvas.description": "Inizia aggiungendo contenuto o scegli un modello professionale",
    "editCard.tabs.elements": "Elementi",
    "editCard.tabs.background": "Sfondo",
    "editCard.tabs.properties": "Proprietà",
    "editCard.elements.text": "Testo",
    "editCard.elements.image": "Immagine",
    "editCard.elements.video": "Video",
    "editCard.elements.gif": "GIF",
    "editCard.elements.textVariables": "Variabili di testo ({{nome}}, {{email}}, ecc.)",
    "editCard.background.backgroundColor": "Colore di sfondo",
    "editCard.background.professionalTemplates": "Modelli Professionali",
    "editCard.background.customBackground": "Immagine di sfondo personalizzata",
    "editCard.properties.title": "Proprietà",
    "editCard.properties.selectedType": "selezionato",
    "editCard.properties.noSelection.title": "Nessun elemento selezionato",
    "editCard.properties.noSelection.description": "Clicca su un elemento nell'editor per modificare le sue proprietà",
    "editCard.properties.text.content": "Contenuto",
    "editCard.properties.text.text": "Testo",
    "editCard.properties.text.size": "Dimensione",
    "editCard.properties.text.color": "Colore",
    "editCard.properties.text.font": "Font (60+ disponibili)",
    "editCard.properties.text.textShadow": "Ombra del testo",
    "editCard.properties.text.alignment": "Allineamento",
    "editCard.properties.text.weight": "Peso",
    "editCard.properties.text.shadowOptions.none": "Nessuna",
    "editCard.properties.text.shadowOptions.light": "Leggera",
    "editCard.properties.text.shadowOptions.medium": "Media",
    "editCard.properties.text.shadowOptions.strong": "Forte",
    "editCard.properties.text.shadowOptions.veryStrong": "Molto forte",
    "editCard.properties.text.shadowOptions.whiteGlow": "Bagliore bianco",
    "editCard.properties.text.shadowOptions.goldGlow": "Bagliore dorato",
    "editCard.properties.text.shadowOptions.blackOutline": "Contorno nero",
    "editCard.properties.text.shadowOptions.goldOutline": "Contorno dorato",
    "editCard.properties.text.alignmentOptions.left": "Sinistra",
    "editCard.properties.text.alignmentOptions.center": "Centro",
    "editCard.properties.text.alignmentOptions.right": "Destra",
    "editCard.properties.text.weightOptions.normal": "Normale",
    "editCard.properties.text.weightOptions.bold": "Grassetto",
    "editCard.properties.text.weightOptions.lighter": "Leggero",
    "editCard.properties.media.base": "Base",
    "editCard.properties.media.width": "Larghezza",
    "editCard.properties.media.height": "Altezza",
    "editCard.properties.media.opacity": "Opacità",
    "editCard.properties.media.rotation": "Rotazione",
    "editCard.properties.media.flip": "Capovolgi",
    "editCard.properties.media.horizontal": "Orizzontale",
    "editCard.properties.media.vertical": "Verticale",
    "editCard.properties.media.style": "Stile",
    "editCard.properties.media.borderRadius": "Raggio del bordo",
    "editCard.properties.media.borderColor": "Colore del bordo",
    "editCard.properties.media.thickness": "Spessore",
    "editCard.properties.media.shadows": "Ombre",
    "editCard.properties.media.enableShadow": "Abilita ombra",
    "editCard.properties.media.shadowColor": "Colore ombra",
    "editCard.properties.media.blur": "Sfocatura",
    "editCard.properties.media.offsetX": "Offset X",
    "editCard.properties.media.offsetY": "Offset Y",
    "editCard.properties.media.filters": "Filtri",
    "editCard.properties.media.brightness": "Luminosità",
    "editCard.properties.media.contrast": "Contrasto",
    "editCard.properties.media.saturation": "Saturazione",
    "editCard.properties.media.grayscale": "Scala di grigi",
    "editCard.properties.media.mediaControls": "Controlli Media",
    "editCard.properties.media.play": "Riproduci",
    "editCard.properties.media.pause": "Pausa",
    "editCard.properties.media.sound": "Suono",
    "editCard.properties.media.mute": "Muto",
    "editCard.properties.media.autoPlay": "Riproduzione automatica",
    "editCard.properties.media.loop": "Loop",
    "editCard.properties.media.useAsBackground": "Usa come sfondo",
    "editCard.properties.deleteElement": "Elimina elemento",
    "editCard.chat.title": "Assistente Design",
    "editCard.chat.subtitle": "IA creativa",
    "editCard.chat.placeholder": "Descrivi la tua carta o chiedi miglioramenti...",
    "editCard.chat.examples": "💡 Esempi: \"carta di compleanno\" o \"migliora il mio design con uno stile moderno\"",
    "editCard.chat.assistant": "Assistente IA",
    "editCard.chat.you": "Tu",
    "editCard.chat.apply": "✅ Applica",
    "editCard.chat.cancel": "↩️ Annulla",
    "editCard.templates.title": "🎨 Modelli Professionali",
    "editCard.templates.subtitle": "20+ design con immagini, bordi vari ed effetto carta realistico",
    "editCard.templates.categories.all": "Tutti",
    "editCard.templates.categories.birthday": "Compleanno",
    "editCard.templates.categories.wedding": "Matrimonio",
    "editCard.templates.categories.baptism": "Battesimo",
    "editCard.templates.categories.easter": "Pasqua",
    "editCard.templates.categories.christmas": "Natale",
    "editCard.templates.categories.elegant": "Elegante",
    "editCard.templates.categories.nature": "Natura",
    "editCard.templates.categories.minimal": "Minimale",
    "editCard.templates.close": "Chiudi",
  },
  de: {
    // Header
    "header.home": "Startseite",
    "header.designs": "Designs",
    "header.pricing": "Preise",
    "header.login": "Anmelden",
    "header.signup": "Registrieren",

    // Hero Section
    "hero.badge": "Premium-Einladungsplattform",
    "hero.title": "Erstellen Sie",
    "hero.title_highlight": "außergewöhnliche Einladungen",
    "hero.description":
      "Verwandeln Sie Ihre Veranstaltungen mit personalisierten Einladungen, die von Experten entworfen wurden. Einfach, schnell und professionell.",
    "hero.start": "Kostenlos starten",
    "hero.models": "Vorlagen anzeigen",
    "hero.models_count": "500+",
    "hero.models_label": "Premium-Vorlagen",
    "hero.clients_count": "25k+",
    "hero.clients_label": "Zufriedene Kunden",
    "hero.rating": "4.9",
    "hero.rating_label": "Kundenbewertungen",

    // Features
    "features.title": "Warum Everblue wählen?",
    "features.description":
      "Entdecken Sie die Funktionen, die unsere Plattform zur idealen Lösung für Ihre besonderen Veranstaltungen machen",
    "features.design": "Anpassbares Design",
    "features.design_desc":
      "Ändern Sie jedes Detail, um eine einzigartige Einladung zu erstellen",
    "features.speed": "Schnelle Erstellung",
    "features.speed_desc":
      "Erstellen Sie professionelle Einladungen in wenigen Minuten",
    "features.download": "Unbegrenzter Download",
    "features.download_desc": "Greifen Sie auf alle Ihre Designs in hoher Qualität zu",
    "features.share": "Einfaches Teilen",
    "features.share_desc":
      "Senden Sie Ihre Einladungen per E-Mail oder in sozialen Medien",

    // Catalog
    "catalog.title": "Unsere Einladungsvorlagen",
    "catalog.description":
      "Entdecken Sie unsere Sammlung von Premium-Vorlagen, die von professionellen Designern für alle Ihre besonderen Veranstaltungen entworfen wurden",
    "catalog.search": "Vorlage suchen...",
    "catalog.all": "Alle",
    "catalog.wedding": "Hochzeit",
    "catalog.birthday": "Geburtstag",
    "catalog.professional": "Beruflich",
    "catalog.christmas": "Weihnachten",
    "catalog.baptism": "Taufe",
    "catalog.party": "Party",
    "catalog.found": "Vorlage(n) gefunden",
    "catalog.filters": "Weitere Filter",
    "catalog.preview": "Vorschau",
    "catalog.customize": "Anpassen",
    "catalog.view_all": "Alle Vorlagen anzeigen",

    // Menu
    "menu.theme": "Design",
    "menu.language": "Sprache",
    "menu.light": "Hell",
    "menu.dark": "Dunkel",

    // EditCard
    "editCard.title": "Professioneller Karten-Editor",
    "editCard.subtitle": "Erstellen Sie atemberaubende Designs mit nur wenigen Klicks",
    "editCard.dragToMove": "Ziehen zum Bewegen",
    "editCard.emptyCanvas.title": "Leere Karte",
    "editCard.emptyCanvas.description": "Beginnen Sie mit dem Hinzufügen von Inhalten oder wählen Sie eine professionelle Vorlage",
    "editCard.tabs.elements": "Elemente",
    "editCard.tabs.background": "Hintergrund",
    "editCard.tabs.properties": "Eigenschaften",
    "editCard.elements.text": "Text",
    "editCard.elements.image": "Bild",
    "editCard.elements.video": "Video",
    "editCard.elements.gif": "GIF",
    "editCard.elements.textVariables": "Textvariablen ({{name}}, {{email}}, etc.)",
    "editCard.background.backgroundColor": "Hintergrundfarbe",
    "editCard.background.professionalTemplates": "Professionelle Vorlagen",
    "editCard.background.customBackground": "Benutzerdefiniertes Hintergrundbild",
    "editCard.properties.title": "Eigenschaften",
    "editCard.properties.selectedType": "ausgewählt",
    "editCard.properties.noSelection.title": "Kein Element ausgewählt",
    "editCard.properties.noSelection.description": "Klicken Sie auf ein Element im Editor, um seine Eigenschaften zu ändern",
    "editCard.properties.text.content": "Inhalt",
    "editCard.properties.text.text": "Text",
    "editCard.properties.text.size": "Größe",
    "editCard.properties.text.color": "Farbe",
    "editCard.properties.text.font": "Schriftart (60+ verfügbar)",
    "editCard.properties.text.textShadow": "Textschatten",
    "editCard.properties.text.alignment": "Ausrichtung",
    "editCard.properties.text.weight": "Gewicht",
    "editCard.properties.text.shadowOptions.none": "Keine",
    "editCard.properties.text.shadowOptions.light": "Leicht",
    "editCard.properties.text.shadowOptions.medium": "Mittel",
    "editCard.properties.text.shadowOptions.strong": "Stark",
    "editCard.properties.text.shadowOptions.veryStrong": "Sehr stark",
    "editCard.properties.text.shadowOptions.whiteGlow": "Weißes Leuchten",
    "editCard.properties.text.shadowOptions.goldGlow": "Goldenes Leuchten",
    "editCard.properties.text.shadowOptions.blackOutline": "Schwarzer Umriss",
    "editCard.properties.text.shadowOptions.goldOutline": "Goldener Umriss",
    "editCard.properties.text.alignmentOptions.left": "Links",
    "editCard.properties.text.alignmentOptions.center": "Mitte",
    "editCard.properties.text.alignmentOptions.right": "Rechts",
    "editCard.properties.text.weightOptions.normal": "Normal",
    "editCard.properties.text.weightOptions.bold": "Fett",
    "editCard.properties.text.weightOptions.lighter": "Leicht",
    "editCard.properties.media.base": "Basis",
    "editCard.properties.media.width": "Breite",
    "editCard.properties.media.height": "Höhe",
    "editCard.properties.media.opacity": "Deckkraft",
    "editCard.properties.media.rotation": "Drehung",
    "editCard.properties.media.flip": "Spiegeln",
    "editCard.properties.media.horizontal": "Horizontal",
    "editCard.properties.media.vertical": "Vertikal",
    "editCard.properties.media.style": "Stil",
    "editCard.properties.media.borderRadius": "Randradius",
    "editCard.properties.media.borderColor": "Randfarbe",
    "editCard.properties.media.thickness": "Dicke",
    "editCard.properties.media.shadows": "Schatten",
    "editCard.properties.media.enableShadow": "Schatten aktivieren",
    "editCard.properties.media.shadowColor": "Schattenfarbe",
    "editCard.properties.media.blur": "Unschärfe",
    "editCard.properties.media.offsetX": "Versatz X",
    "editCard.properties.media.offsetY": "Versatz Y",
    "editCard.properties.media.filters": "Filter",
    "editCard.properties.media.brightness": "Helligkeit",
    "editCard.properties.media.contrast": "Kontrast",
    "editCard.properties.media.saturation": "Sättigung",
    "editCard.properties.media.grayscale": "Graustufen",
    "editCard.properties.media.mediaControls": "Mediensteuerung",
    "editCard.properties.media.play": "Abspielen",
    "editCard.properties.media.pause": "Pause",
    "editCard.properties.media.sound": "Ton",
    "editCard.properties.media.mute": "Stumm",
    "editCard.properties.media.autoPlay": "Automatische Wiedergabe",
    "editCard.properties.media.loop": "Schleife",
    "editCard.properties.media.useAsBackground": "Als Hintergrund verwenden",
    "editCard.properties.deleteElement": "Element löschen",
    "editCard.chat.title": "Design-Assistent",
    "editCard.chat.subtitle": "Kreative KI",
    "editCard.chat.placeholder": "Beschreiben Sie Ihre Karte oder bitten Sie um Verbesserungen...",
    "editCard.chat.examples": "💡 Beispiele: \"Geburtstagskarte\" oder \"verbessere mein Design mit einem modernen Stil\"",
    "editCard.chat.assistant": "KI-Assistent",
    "editCard.chat.you": "Sie",
    "editCard.chat.apply": "✅ Anwenden",
    "editCard.chat.cancel": "↩️ Abbrechen",
    "editCard.templates.title": "🎨 Professionelle Vorlagen",
    "editCard.templates.subtitle": "20+ Designs mit Bildern, verschiedenen Rändern und realistischem Papiereffekt",
    "editCard.templates.categories.all": "Alle",
    "editCard.templates.categories.birthday": "Geburtstag",
    "editCard.templates.categories.wedding": "Hochzeit",
    "editCard.templates.categories.baptism": "Taufe",
    "editCard.templates.categories.easter": "Ostern",
    "editCard.templates.categories.christmas": "Weihnachten",
    "editCard.templates.categories.elegant": "Elegant",
    "editCard.templates.categories.nature": "Natur",
    "editCard.templates.categories.minimal": "Minimal",
    "editCard.templates.close": "Schließen",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language | null;
    return saved || "fr";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return (
      translations[language][key as keyof (typeof translations)[Language]] ||
      key
    );
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
